name: TeamCity deployment

on: push

jobs:
  # Собирается бекенд и деплоится на стейдж/review app
  backend:
    uses: ./.github/workflows/backend-stage.yml

  # Собирается бекенд и деплоится на стейдж/review app
  frontend:
    uses: ./.github/workflows/frontend-stage.yml

  # Прогоняются API тесты
  automation-api:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: api

  # Прогоняются UI тесты
  automation-ui:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui

  # Wait for manual approval from authorized users
  manual-prod-approval:
    needs: [automation-ui, automation-api]
    runs-on: ubuntu-latest
    environment: 'production'
    steps:
      - name: Approve backend and frontend to production
        run: echo Release approved

  # If approval is successful, proceed with the production deployment
  deploy-prod:
    needs: manual-prod-approval
    uses: ./.github/workflows/deploy-prod.yml
